name: env_tutorial

on: [pull_request, push]
jobs:
 job1:
    runs-on: ubuntu-latest
    steps:
    - name: step 1
      env:
       API_KEY: XXXXXXXXXXXX
      run: echo "The API key is:${{env.API_KEY}}"
    - name: step 2
      run: echo "The API key is:${{env.API_KEY}}" 
